apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  namespace: forge-ops
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "forge-ops"
    vault.hashicorp.com/agent-inject-secret-user-service: "secret/data/user-service"
spec:
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]